services:
  nodelink:
    image: performanc/nodelink:3.6.0
    container_name: nodelink_app
    ports:
      - "2333:3000"
    environment:
      # --- Server Configuration ---
      NODELINK_SERVER_HOST: "0.0.0.0"
      NODELINK_SERVER_PORT: "3000"
      NODELINK_SERVER_PASSWORD: "youshallnotpass" # CHANGE THIS!
      NODELINK_VOICERECEIVE_ENABLED: "true"
      NODELINK_VOICERECEIVE_FORMAT: "pcm_s16le"
  nodelink-1:
    image: performanc/nodelink:3.6.0
    container_name: nodelink_app-1
    ports:
      - "2334:3000"
    environment:
      # --- Server Configuration ---
      NODELINK_SERVER_HOST: "0.0.0.0"
      NODELINK_SERVER_PORT: "3000"
      NODELINK_SERVER_PASSWORD: "youshallnotpass" # CHANGE THIS!
      NODELINK_VOICERECEIVE_ENABLED: "true"
      NODELINK_VOICERECEIVE_FORMAT: "pcm_s16le"
  nodelink-2:
    image: performanc/nodelink:3.6.0
    container_name: nodelink_app-2
    ports:
      - "2335:3000"
    environment:
      # --- Server Configuration ---
      NODELINK_SERVER_HOST: "0.0.0.0"
      NODELINK_SERVER_PORT: "3000"
      NODELINK_SERVER_PASSWORD: "youshallnotpass" # CHANGE THIS!
      NODELINK_VOICERECEIVE_ENABLED: "true"
      NODELINK_VOICERECEIVE_FORMAT: "pcm_s16le"