apiVersion: v1
kind: ConfigMap
metadata:
  name: rosetta-config
  namespace: rosetta
  annotations:
    avp.kubernetes.io/secret: "rosetta:rosetta-secret"
data:
  config.ini: |
    [bot]
    TOKEN=<{{ .discord-client-secret }}>
    CLIENT_ID=1091392369296937073
    [langfuse]
    PUBLIC_KEY=<{{ .langfuse-public-key }}>
    SECRET_KEY=<{{ .langfuse-secret-key }}>
    HOST=https://langfuse.andyjjrt.cc
    [llm]
    BASE_URL=https://llm.andyjjrt.cc
    API_KEY=<{{ .llm-api-key }}>
    DEFAULT_MODEL=Qwen3-4B-Instruct-2507.Eagle3
    [bot.emoji]
    success=<a:success:1349071419581005897>
    error=<a:error:1349071449633329352>
    youtube=<:youtube:1349071467773431818>
    progress_start=<:progress_start:1349071486673096766>
    progress=<:progress:1349071500195397744>
    progress_mix=<:progress_mix:1349071514464419911>
    progress_fill=<:progress_fill:1349071527559036958>
    progress_end=<:progress_end:1349071541098381322>
    progress_fill_end=<:progress_fill_end:1349071554360905748>
    progress_start_0=<:progress_start_0:1349071577584767043>
