kind: Secret
apiVersion: v1
metadata:
  name: rosetta-secret
  namespace: rosetta
  annotations:
    avp.kubernetes.io/path: "rosetta:rosetta-secret"
type: Opaque
stringData:
  discord-client-secret: <discord-client-secret>
  langfuse-public-key: <langfuse-public-key>
  langfuse-secret-key: <langfuse-secret-key>
  llm-api-key: <llm-api-key>