# log_config.yaml
version: 1
disable_existing_loggers: false

formatters:
  default:
    "fmt": "%(message)s"

handlers:
  # Handler for general/error logs, using RichHandler
  rich_error_handler:
    class: rich.logging.RichHandler
    formatter: default
    level: INFO
    # Custom options for RichHandler's tracebacks
    markup: true
    rich_tracebacks: true
    omit_repeated_times: false
    show_path: false
    tracebacks_word_wrap: false

loggers:
  # Root logger configuration
  rosetta:
    level: INFO
    handlers: [rich_error_handler] # All uvicorn logs will use this by default
    propagate: no